### PR TITLE
feat: update for Talos 1.0

### PR DESCRIPTION
**Pull request by smira**
Update machinery dependency, compatibility matrix for Talos 1.0.

Signed-off-by: Andrey Smirnov <andrey.smirnov@talos-systems.com>

### CODE REVIEW

**Review by Unix4ever — APPROVED** [review]
And I think it probably makes sense to also bump CABPT to 0.5.3

**Comment by smira** [comment]
> And I think it probably makes sense to also bump CABPT to 0.5.3

oh yeah, forgot that totally!

**Comment by smira** [comment]
> And I think it probably makes sense to also bump CABPT to 0.5.3

I think we should also bump capi-utils to the latest CAPI core and use that in our providers (1.1.3)

**Comment by Unix4ever** [comment]
> I think we should also bump capi-utils to the latest CAPI core and use that in our providers (1.1.3)

Right, let me do it :)

**Pull request merged**
